In [3]:
import numpy as np

In [5]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
arr2 = np.arange(start=0, stop=10)
print(arr2)

arr3 = np.arange(0, 10)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr4 = np.arange(0,20,5)
print(arr4)

[ 0  5 10 15]


In [ ]:
matrix2 = np.linspace(0,5) #default number of steps is 50
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [13]:
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
matrix5 = np.zeros([4, 4])
matrix5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones([3, 5], int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
matrix6 = np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr1 = np.arange(0, 20, 3)
arr1

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
matrix_a = np.linspace(10, 20, 10)
matrix_a

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [22]:
arr4 = np.arange(0, 10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr4_reshaped = arr4.reshape([2,5])
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
print(len(arr4))

10


**Trigonometric functions**

In [29]:
print("Sine Function: ", np.sin(4))
print("Cosine Function: ", np.cos(4))
print("Tan Function: ", np.tan(4))

Sine Function:  -0.7568024953079282
Cosine Function:  -0.6536436208636119
Tan Function:  1.1578212823495777


**Exponents and logarithmic functions**

In [30]:
np.exp(2)

7.38905609893065

In [31]:
arr5 = np.array([2, 4, 6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [ ]:
#by default Numpty takes the base of log as e
np.log(2)

0.6931471805599453

In [33]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [34]:
#log with base 10
np.log10(8)

0.9030899869919435

**Arithmetic operations on arrays**

In [35]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [39]:
arr7 = np.arange(1,6)
print("arr7: ", arr7)

arr8 = np.arange(3, 8)
print("arr8: ", arr8)


arr7:  [1 2 3 4 5]
arr8:  [3 4 5 6 7]


In [42]:
print("Addition: ", arr7+arr8)
print("Subtraction: ", arr8 - arr7)
print("Multiplication: ", arr8 * arr7)
print("Divide: ", arr7 / arr8)
print("Inverse: ", 1/arr7)
print("Powers: ", arr7 ** arr8)

Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication:  [ 3  8 15 24 35]
Divide:  [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse:  [1.         0.5        0.33333333 0.25       0.2       ]
Powers:  [    1    16   243  4096 78125]


In [43]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [44]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

***Operations on Matrices**

In [45]:
matrix7 = np.arange(1, 10).reshape(3, 3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
print("Addition: \n", matrix7 + matrix8)
print("Subtraction: \n", matrix7 - matrix8)
print("Multiplication: \n", matrix7 * matrix8)
print("Division: \n", matrix7 / matrix8)

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


C:\Users\brosb\AppData\Local\Temp\ipykernel_6232\799586902.py:4: RuntimeWarning: divide by zero encountered in divide
  print("Division: \n", matrix7 / matrix8)


**Linear Algebra Matrix Multiplication**

In [50]:
matrix9 = np.arange(1,10).reshape([3,3])

print("First Matrix: \n", matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print("Second Matrix: \n", matrix10)

print("Multiplication: \n", matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


**Transpose of a matrix**

In [51]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Function to find minimum and maximum values**

In [54]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print("Minimum value: ", np.min(matrix9))

print("Maximum value: ", np.max(matrix9))

Minimum value:  1
Maximum value:  9


**Functions to generate random samples**

In [57]:
rand_mat = np.random.rand(5)
print(rand_mat)

[0.34945757 0.55619098 0.3964671  0.07966777 0.47134617]


In [58]:
#Generating random values in a matrix
rand_mat2 = np.random.rand(5, 5)
print(rand_mat2)


[[0.2705711  0.26498621 0.31193928 0.18912073 0.66991301]
 [0.2098272  0.51719568 0.65487754 0.65908795 0.29180371]
 [0.45945178 0.29475814 0.02078671 0.91582808 0.21491028]
 [0.31464384 0.4275126  0.19185867 0.00959691 0.27160208]
 [0.9023772  0.67669765 0.52273797 0.44617021 0.20478672]]


**Using np.random.randn function**

- The np.random.randn returns a random numpy array whose samples(s) are drawn randomly from the standard normal distribution (Mean = 0, standard deviation = 1)

-*Syntax* - np.random.randn(d0,d1)
    - d0, d1 represent the dimension of the output with d1 being optional

In [60]:
rand_mat3 = np.random.randn(5)
print(rand_mat3)

[ 0.25884217 -0.6438908  -0.69859039  0.53871419 -0.94799502]


In [ ]:
rand_mat4 = np.random.randn(5, 5)
print(rand_mat4)

[[-0.31227551  0.45149453 -1.13054943 -1.47621781 -0.97954678]
 [-1.04178933  0.59759262 -0.86528744  0.06330064 -0.54253861]
 [ 1.40021015  0.49288669 -0.1797819   0.34754639 -0.10486836]
 [-0.0286328  -0.7181313   0.06656057  0.01860902  0.25430555]
 [-0.89302576 -1.71566375  0.66589012 -0.60537286 -0.69048025]]


In [62]:
#Let's check the mean and standard deviation of rand_mat4
print("Mean: ", np.mean(rand_mat4))
print("Standard deviation: ", np.std(rand_mat4))

Mean:  -0.27703062427446246
Standard deviation:  0.7285702705982608


In [63]:
rand_mat5 = np.random.randn(500,500)

print("Mean: ", np.mean(rand_mat5))
print("Standard deviation: ", np.std(rand_mat5))

Mean:  0.00031854194283471475
Standard deviation:  1.0002573963685693


**Using np.random.randint function**
-The np.random.randint returns a random numpy array whose element(s) are drawn randomly from low(inclusive) to the high (exclusive) range

In [64]:
rand_mat6 = np.random.randint(1, 5, 10)
print(rand_mat6)

[2 2 4 3 4 4 1 4 4 1]


In [65]:
rand_mat7 = np.random.randint(1, 10, [5,5])
print(rand_mat7)

[[7 4 6 4 3]
 [9 6 9 1 8]
 [3 2 8 5 7]
 [6 3 6 3 7]
 [8 4 4 6 7]]
