In [3]:
import numpy as np

In [5]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
arr2 = np.arange(start=0, stop=10)
print(arr2)

arr3 = np.arange(0, 10)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [10]:
arr4 = np.arange(0,20,5)
print(arr4)

[ 0  5 10 15]


In [ ]:
matrix2 = np.linspace(0,5) #default number of steps is 50
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [13]:
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
matrix5 = np.zeros([4, 4])
matrix5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones([3, 5], int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
matrix6 = np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr1 = np.arange(0, 20, 3)
arr1

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
matrix_a = np.linspace(10, 20, 10)
matrix_a

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [22]:
arr4 = np.arange(0, 10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr4_reshaped = arr4.reshape([2,5])
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
print(len(arr4))

10


**Trigonometric functions**

In [29]:
print("Sine Function: ", np.sin(4))
print("Cosine Function: ", np.cos(4))
print("Tan Function: ", np.tan(4))

Sine Function:  -0.7568024953079282
Cosine Function:  -0.6536436208636119
Tan Function:  1.1578212823495777


**Exponents and logarithmic functions**

In [30]:
np.exp(2)

7.38905609893065

In [31]:
arr5 = np.array([2, 4, 6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [ ]:
#by default Numpty takes the base of log as e
np.log(2)

0.6931471805599453

In [33]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [34]:
#log with base 10
np.log10(8)

0.9030899869919435

**Arithmetic operations on arrays**

In [35]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [39]:
arr7 = np.arange(1,6)
print("arr7: ", arr7)

arr8 = np.arange(3, 8)
print("arr8: ", arr8)


arr7:  [1 2 3 4 5]
arr8:  [3 4 5 6 7]


In [42]:
print("Addition: ", arr7+arr8)
print("Subtraction: ", arr8 - arr7)
print("Multiplication: ", arr8 * arr7)
print("Divide: ", arr7 / arr8)
print("Inverse: ", 1/arr7)
print("Powers: ", arr7 ** arr8)

Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication:  [ 3  8 15 24 35]
Divide:  [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse:  [1.         0.5        0.33333333 0.25       0.2       ]
Powers:  [    1    16   243  4096 78125]
