In [65]:
import numpy as np

In [66]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [67]:
list(range(5,20))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [68]:
arr2 = np.arange(start=0, stop=10)
print(arr2)

arr3 = np.arange(0, 10)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [74]:
arrA = np.arange(14,21)
print(arrA)

[14 15 16 17 18 19 20]


In [73]:
arrB = np.arange(7,14)
print(arrB)

[ 7  8  9 10 11 12 13]


In [75]:
print(arrA+arrB)

[21 23 25 27 29 31 33]


In [76]:
arr4 = np.arange(0,20,5)
print(arr4)

[ 0  5 10 15]


In [77]:
matrix2 = np.linspace(0,5) #default number of steps is 50
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [82]:
matA = np.linspace(1,20,10).reshape(2,5)
print(matA)

[[ 1.          3.11111111  5.22222222  7.33333333  9.44444444]
 [11.55555556 13.66666667 15.77777778 17.88888889 20.        ]]


In [83]:
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [84]:
matrix4 = np.zeros([3,5])
matrix4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [85]:
matrix5 = np.zeros([4, 4])
matrix5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
np.ones([3, 5], int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [87]:
matrix6 = np.eye(5)
matrix6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
arr1 = np.arange(0, 20, 3)
arr1

array([ 0,  3,  6,  9, 12, 15, 18])

In [89]:
matrix_a = np.linspace(10, 20, 10)
matrix_a

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [90]:
arr4 = np.arange(0, 10)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr4_reshaped = arr4.reshape([2,5])
arr4_reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [92]:
print(len(arr4))

10


**Trigonometric functions**

In [93]:
print("Sine Function: ", np.sin(4))
print("Cosine Function: ", np.cos(4))
print("Tan Function: ", np.tan(4))

Sine Function:  -0.7568024953079282
Cosine Function:  -0.6536436208636119
Tan Function:  1.1578212823495777


**Exponents and logarithmic functions**

In [94]:
np.exp(2)

7.38905609893065

In [95]:
arr5 = np.array([2, 4, 6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [96]:
#by default Numpty takes the base of log as e
np.log(2)

0.6931471805599453

In [97]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [98]:
#log with base 10
np.log10(8)

0.9030899869919435

**Arithmetic operations on arrays**

In [99]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
print(l1+l2)

[1, 2, 3, 4, 5, 6]


In [100]:
arr7 = np.arange(1,6)
print("arr7: ", arr7)

arr8 = np.arange(3, 8)
print("arr8: ", arr8)


arr7:  [1 2 3 4 5]
arr8:  [3 4 5 6 7]


In [101]:
print("Addition: ", arr7+arr8)
print("Subtraction: ", arr8 - arr7)
print("Multiplication: ", arr8 * arr7)
print("Divide: ", arr7 / arr8)
print("Inverse: ", 1/arr7)
print("Powers: ", arr7 ** arr8)

Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication:  [ 3  8 15 24 35]
Divide:  [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse:  [1.         0.5        0.33333333 0.25       0.2       ]
Powers:  [    1    16   243  4096 78125]


In [102]:
np.array([1, 2, 3]) + np.array([4, 5, 6])

array([5, 7, 9])

In [103]:
np.array([1, 2, 3]) * np.array([4, 5, 6])

array([ 4, 10, 18])

***Operations on Matrices**

In [104]:
matrix7 = np.arange(1, 10).reshape(3, 3)
print(matrix7)

matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [105]:
print("Addition: \n", matrix7 + matrix8)
print("Subtraction: \n", matrix7 - matrix8)
print("Multiplication: \n", matrix7 * matrix8)
print("Division: \n", matrix7 / matrix8)

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


C:\Users\brosb\AppData\Local\Temp\ipykernel_2136\799586902.py:4: RuntimeWarning: divide by zero encountered in true_divide
  print("Division: \n", matrix7 / matrix8)


**Linear Algebra Matrix Multiplication**

In [106]:
matrix9 = np.arange(1,10).reshape([3,3])

print("First Matrix: \n", matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print("Second Matrix: \n", matrix10)

print("Multiplication: \n", matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


**Transpose of a matrix**

In [107]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [108]:
print(matrix9.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [109]:
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [110]:
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Function to find minimum and maximum values**

In [35]:
print(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
print("Minimum value: ", np.min(matrix9))

print("Maximum value: ", np.max(matrix9))

Minimum value:  1
Maximum value:  9


**Functions to generate random samples**

In [112]:
rand_mat = np.random.rand(5)
print(rand_mat)

[0.16187056 0.54331688 0.57933578 0.29787613 0.8326538 ]


In [113]:
#Generating random values in a matrix
rand_mat2 = np.random.rand(5, 5)
print(rand_mat2)


[[0.5975483  0.91845399 0.01031675 0.80970253 0.05869674]
 [0.35579351 0.3998296  0.89138665 0.48303477 0.80336101]
 [0.88772387 0.81869159 0.30036335 0.83149484 0.40821524]
 [0.9803201  0.79875861 0.9178396  0.21346782 0.51379173]
 [0.91083261 0.07483507 0.95181775 0.78511832 0.63490715]]


**Using np.random.randn function**

- The np.random.randn returns a random numpy array whose samples(s) are drawn randomly from the standard normal distribution (Mean = 0, standard deviation = 1)

-*Syntax* - np.random.randn(d0,d1)
    - d0, d1 represent the dimension of the output with d1 being optional

In [121]:
rand_mat3 = np.random.randn(5)
print(rand_mat3)

[-1.1330796   0.727883   -0.66997633  0.42126731 -0.4546396 ]


In [122]:
rand_mat4 = np.random.randn(5, 5)
print(rand_mat4)

[[-0.44157709 -0.80421291 -0.13538872  1.05060708 -0.37371505]
 [-0.68659915 -0.82016263 -0.32021324 -2.23551191  0.86196328]
 [-0.78755442 -0.33154381 -0.6226227   0.18208441 -0.04521952]
 [ 0.75167454  0.71865334 -0.63511138 -1.27140337 -0.08906465]
 [ 0.85724063 -0.8053992  -1.23359452  1.6674594   0.96861136]]


In [123]:
#Let's check the mean and standard deviation of rand_mat4
print("Mean: ", np.mean(rand_mat4))
print("Standard deviation: ", np.std(rand_mat4))

Mean:  -0.18322400934578187
Standard deviation:  0.8749293708335171


In [124]:
matRandA = np.random.randn(1000,1000)
print("Mean: ", np.mean(matRandA))
print("Standard deviation: ", np.std(matRandA))

Mean:  4.7362336794278574e-05
Standard deviation:  1.0002837528391604


In [125]:
rand_mat5 = np.random.randn(500,500)

print("Mean: ", np.mean(rand_mat5))
print("Standard deviation: ", np.std(rand_mat5))

Mean:  0.00027457416330770783
Standard deviation:  1.000358934585753


**Using np.random.randint function**
-The np.random.randint returns a random numpy array whose element(s) are drawn randomly from low(inclusive) to the high (exclusive) range

In [126]:
rand_mat6 = np.random.randint(1, 5, 10)
print(rand_mat6)

[1 3 2 3 4 1 3 2 2 3]


In [127]:
rand_mat7 = np.random.randint(1, 10, [5,5])
print(rand_mat7)

[[7 6 3 3 4]
 [5 5 6 3 1]
 [1 4 4 9 8]
 [3 1 3 9 4]
 [9 5 7 2 3]]


In [128]:
rand_mat8 = np.random.randn(10)
rand_mat8
rand_mat8[6] #Access the 7th element

0.7091719685024501

In [129]:
rand_mat8

array([ 0.45463629, -0.82840338,  0.26413982,  0.18490772,  0.44101243,
       -1.51164342,  0.70917197,  0.98245027, -1.01497901, -0.40851273])

In [130]:
#Access the 5th to 10th item
rand_mat8[4:9]

array([ 0.44101243, -1.51164342,  0.70917197,  0.98245027, -1.01497901])

In [131]:
rand_mat8

array([ 0.45463629, -0.82840338,  0.26413982,  0.18490772,  0.44101243,
       -1.51164342,  0.70917197,  0.98245027, -1.01497901, -0.40851273])

In [132]:
print("Values greater than 0:", rand_mat8[rand_mat8 > 0])

Values greater than 0: [0.45463629 0.26413982 0.18490772 0.44101243 0.70917197 0.98245027]


In [133]:
print("Values less than 0:", rand_mat8[rand_mat8 < 0])

Values less than 0: [-0.82840338 -1.51164342 -1.01497901 -0.40851273]


In [134]:
rand_mat9 = np.random.randn(20)
rand_mat9

array([-1.54712561, -0.01840426, -1.57613373,  0.72578875, -1.11923067,
       -0.39647425,  0.43582071,  0.9238561 , -0.64374751,  0.49310355,
       -1.36692253, -1.11077646, -0.18575348, -0.74436281, -0.00601417,
       -1.82951282,  1.28505947, -1.92548489,  1.28841541,  0.36966878])

In [135]:
rand_mat10 = np.random.randint(3,10,10)
rand_mat10

array([6, 6, 7, 7, 7, 6, 9, 6, 5, 7])

In [136]:
rand_mat10 > 5

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True])

In [137]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
print(matrix[0][0])

1


In [139]:
print(matrix[0][1])

2


In [140]:
print(matrix[1][1])

5


In [141]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [64]:
vec1 = np.array([4,7,8,9,10,6,1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [145]:
rand_mat3 = np.random.randint(0,10,[5,5])
print(rand_mat3)

[[7 6 4 0 8]
 [3 5 7 6 6]
 [7 3 8 9 4]
 [0 9 7 4 4]
 [1 8 3 4 0]]


In [148]:
rand_mat3[1]

array([3, 5, 7, 6, 6])

In [147]:
rand_mat3[1][1]

5

In [149]:
rand_mat3[1,2]

7

In [150]:
print("Matrix before modification: \n", rand_mat3)

Matrix before modification: 
 [[7 6 4 0 8]
 [3 5 7 6 6]
 [7 3 8 9 4]
 [0 9 7 4 4]
 [1 8 3 4 0]]


In [161]:
rand_mat3[1:3,3:5] = 0
print("Matrix after modification: ", rand_mat3)

Matrix after modification:  [[7 6 4 0 8]
 [3 5 7 0 0]
 [7 3 8 0 0]
 [0 9 7 4 4]
 [1 8 3 4 0]]


In [164]:
sub_mat3 = rand_mat3[0:2,0:3]

In [165]:
print(sub_mat3)

[[7 6 4]
 [3 5 7]]


In [166]:
sub_mat3[:] = 3
print(sub_mat3)

[[3 3 3]
 [3 3 3]]


In [167]:
print(rand_mat3)

[[3 3 3 0 8]
 [3 3 3 0 0]
 [7 3 8 0 0]
 [0 9 7 4 4]
 [1 8 3 4 0]]


In [171]:
rand_mat = np.random.randn(5,5)
print(rand_mat)
sub_mat = rand_mat[0:2,0:3].copy()
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)
print(rand_mat)

[[-1.66232907  0.62656175  0.11011108 -0.24397761  1.66934466]
 [-1.13948905 -0.74296847  0.79598358  0.42811308 -1.44860092]
 [ 0.33709188  0.99082593 -0.09156312 -0.56344182 -2.30251064]
 [ 0.11791901 -1.25621304 -0.34013618  0.54274469 -0.16201649]
 [ 0.09581254 -0.84324627 -0.39075099  0.2007485  -0.88013146]]
[[-1.66232907  0.62656175  0.11011108]
 [-1.13948905 -0.74296847  0.79598358]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[-1.66232907  0.62656175  0.11011108 -0.24397761  1.66934466]
 [-1.13948905 -0.74296847  0.79598358  0.42811308 -1.44860092]
 [ 0.33709188  0.99082593 -0.09156312 -0.56344182 -2.30251064]
 [ 0.11791901 -1.25621304 -0.34013618  0.54274469 -0.16201649]
 [ 0.09581254 -0.84324627 -0.39075099  0.2007485  -0.88013146]]


In [173]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [174]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)
array2 = array1
array2[1:2,0:2] = 4
print(array2)
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 4 6]
 [7 8 9]]
[[1 2 3]
 [4 4 6]
 [7 8 9]]
