<a href="https://colab.research.google.com/github/chemkemeimyers/PythonProjects/blob/main/SavingNLoadingNumpyArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import numpy as np

In [8]:
randint_matrix1 = np.random.randint(1,10,10).reshape(2,5)
print(randint_matrix1)
print("")
randint_matrix2 = np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)


[[8 8 9 4 5]
 [8 5 5 4 9]]

[[18 15 16 19 14]
 [18 11 11 17 10]]


In [11]:
np.save("/content/drive/MyDrive/MachineLearningCourse/Python/MatrixData",randint_matrix1)

In [12]:
np.savez("/content/drive/MyDrive/MachineLearningCourse/Python/multiple_files",
         randint_matrix1 = randint_matrix1,
         randint_matrix2 = randint_matrix2)

In [13]:
loaded_arr = np.load("/content/drive/MyDrive/MachineLearningCourse/Python/MatrixData.npy")
print(loaded_arr)

[[8 8 9 4 5]
 [8 5 5 4 9]]


In [14]:
loaded_multi = np.load("/content/drive/MyDrive/MachineLearningCourse/Python/multiple_files.npz")

In [16]:
print(loaded_multi["randint_matrix1"])
print(loaded_multi["randint_matrix2"])

[[8 8 9 4 5]
 [8 5 5 4 9]]
[[18 15 16 19 14]
 [18 11 11 17 10]]


In [17]:
np.savetxt("/content/drive/MyDrive/MachineLearningCourse/Python/matrix_data.txt",randint_matrix1,delimiter=",")

In [18]:
rand_mat_txt = np.loadtxt("/content/drive/MyDrive/MachineLearningCourse/Python/matrix_data.txt",delimiter=",")
print(rand_mat_txt)

[[8. 8. 9. 4. 5.]
 [8. 5. 5. 4. 9.]]
